export type PlayerType = {
  id: number;
  username: string;
  uuid: string;
  email: string | null;
  emailIsConfirmed: boolean;
  lastIp?: string;
  avatar_img: string | null;
  lastLoginDate?: string;
  registrationDate: string;
  cityId?: string | null;
  stateId?: string | null;
  cityName?: string | null;
  stateName?: string | null;
  citizenshipName?: string | null;
  stateFlagUrl?: string | null;
  stateCoatOfArmsUrl?: string | null;
  nationalityMale?: string | null;
  nationalityFemale?: string | null;
  role?: "player" | "economist" | "admin";
  isAdmin?: boolean;
  isEconomist?: boolean;
};
